[package]
name = "simple-prompt"
version = "0.1.0"
authors = ["Jared Wolff <hello@jaredwolff.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
